# # TiDB Cloud Database Connection
# spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/currency_app?useSSL=true&requireSSL=true
# spring.datasource.username=22FkrxdyTyc5VWD.root
# spring.datasource.password=MmZ3xd3CZC1FEjLv
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# # Hibernate Settings
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true


# TiDB Cloud Database Connection (Secured with Environment Variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
